### ISSUE TITLE
Problem DatePicker :bug:

### ISSUE THREAD

**Issue by GuillaumePiers** [menatwork/contao-multicolumnwizard-bundle#2]
Hello,

In EventListener/Mcw/DatePicker.php (https://github.com/menatwork/contao-multicolumnwizard-bundle/blob/master/src/EventListener/Mcw/DatePicker.php) line 72 :
`if ($fieldConfiguration['eval']['submitOnChange']) {`
make me an error with Contao 4.13. I replace by :
`if (isset($fieldConfiguration['eval']['submitOnChange']) && $fieldConfiguration['eval']['submitOnChange']) {`
and it's work!

**Comment by zonky2** [comment]
@GuillaumePiers Please add an PR with your changes and add your config to check this warning

**Comment by zonky2** [comment]
Fixed
